spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:auth-db}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

auth-service:
  jwt:
    private-key-path: keys/private_pkcs8.pem
    public-key-path: keys/public.pem

logging:
  level:
    org.springframework.security: trace

server:
  port: 8081